#!/usr/bin/env python3
"""Embed pinned reconstructed DSP filter words without runtime file access."""
import argparse
import hashlib
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
SHA256 = 'd7741279c2e8ec5c5fb318f8fbdd6de6bf583520d288e836a5383233a4238179'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = (ROOT / 'third_party/dolphin_dsp/dsp_coef.bin').read_bytes()
    if len(data) != 4096 or hashlib.sha256(data).hexdigest() != SHA256:
        raise SystemExit('DSP coefficient input does not match the pinned dependency')
    # The last 512 words are outside the AX resampler's three filter banks.
    words = struct.unpack('>1536h', data[:3072])
    text = ('/* Generated by tools/prepare_ax_coefficients.py.\n'
            ' * Reconstructed Dolphin DSP data; see third_party/dolphin_dsp. */\n'
            'static const s16 native_ax_coefficients[1536] = {\n')
    text += ''.join('    ' + ', '.join(str(v) for v in words[i:i+8]) + ',\n'
                    for i in range(0, len(words), 8))
    text += '};\n'
    output = ROOT / 'src/ax_coefficients.inc'
    if args.check:
        if not output.exists() or output.read_text() != text:
            raise SystemExit('Embedded DSP coefficients are stale; run this script without --check')
    else:
        output.write_text(text)


if __name__ == '__main__':
    main()
