"""C translation units shared by the Apple host and its integration tests.

GameCube hardware implementations are intentionally not linked. Portable SDK
C math bodies are retained, with their PPC entry points provided by the native
backend. This list is not the full game and must not be presented as one.
"""
SOURCES = [f'native/src/{name}.c' for name in [
    'archive', 'sis_bank', 'camera', 'lights', 'rumble_bank', 'mth_header', 'sem', 'ssm', 'ai_backend', 'card_store', 'card_icons', 'card_backend', 'devkit_backend', 'vi_backend', 'ax_itd', 'input', 'pad_backend', 'os_interrupt', 'hsd_input', 'mtx_backend',
    'diagnostics', 'audio_producer', 'audio_ring', 'ax_voice_backend', 'ax_decode', 'ax_mix', 'ax_output', 'ax_stream', 'ax_pool_mix', 'ax_depop', 'ax_aux_backend', 'reverb_std_backend', 'reverb_hi_backend', 'settings_backend', 'os_boot_backend', 'reset_backend', 'alarm_backend', 'runtime_backend', 'time_backend', 'heap_backend', 'animation', 'disc', 'dvd_backend', 'aram_backend', 'cache_backend', 'texture', 'joint', 'pose', 'vertex', 'skin', 'model', 'material', 'gx_pixel', 'visibility', 'action',
]] + [
    'extern/dolphin/src/dolphin/ar/arq.c',
    'extern/dolphin/src/dolphin/ax/AXAlloc.c',
    'extern/dolphin/src/dolphin/ax/AXAux.c',
    'extern/dolphin/src/dolphin/ax/AXVPB.c',
    'extern/dolphin/src/dolphin/axfx/axfx.c',
    'extern/dolphin/src/dolphin/axfx/delay.c',
    'extern/dolphin/src/dolphin/axfx/chorus.c',
    'extern/dolphin/src/dolphin/os/OSArena.c',
    'extern/dolphin/src/dolphin/os/OSTime.c',
    'src/MSL/float.c',
    'src/sysdolphin/baselib/debug.c',
    'src/sysdolphin/baselib/devcom.c',
    'src/sysdolphin/baselib/controller.c',
    'src/sysdolphin/baselib/rumble.c',
    'src/sysdolphin/baselib/memory.c',
    'src/sysdolphin/baselib/objalloc.c',
    'src/sysdolphin/baselib/fobj.c',
    'src/sysdolphin/baselib/aobj.c',
    'src/melee/lb/lbanim.c',
    'src/melee/lb/lbcommand.c',
    'src/melee/ft/ftaction.c',
    'src/melee/ft/ftparts.c',
    'src/melee/ft/kinds/ftMario/ftmario.c',
    'src/melee/ft/kinds/ftFox/ftfox.c',
    'src/melee/ft/kinds/ftPeach/ftpeach.c',
    'src/melee/ft/kinds/ftGameWatch/ftgamewatch.c',
    'src/melee/ft/kinds/ftKirby/ftkirby.c',
    'src/sysdolphin/baselib/dobj.c',
    'src/sysdolphin/baselib/spline.c',
    'src/sysdolphin/baselib/mtx.c',
    'src/sysdolphin/baselib/class.c',
    'src/sysdolphin/baselib/object.c',
    'src/sysdolphin/baselib/hash.c',
    'src/sysdolphin/baselib/id.c',
    'src/sysdolphin/baselib/jobj.c',
    'src/sysdolphin/baselib/displayfunc.c',
    'src/sysdolphin/baselib/tobj.c',
    'src/sysdolphin/baselib/state.c',
    'src/sysdolphin/baselib/robj.c',
    'src/sysdolphin/baselib/bytecode.c',
    'src/sysdolphin/baselib/util.c',
    'src/sysdolphin/baselib/list.c',
    'src/sysdolphin/baselib/random.c',
    'src/sysdolphin/baselib/gobj.c',
    'src/sysdolphin/baselib/gobjinit.c',
    'src/sysdolphin/baselib/gobjproc.c',
    'src/sysdolphin/baselib/gobjplink.c',
    'src/sysdolphin/baselib/gobjgxlink.c',
    'src/sysdolphin/baselib/gobjobject.c',
    'src/sysdolphin/baselib/gobjuserdata.c',
] + [f'extern/dolphin/src/dolphin/mtx/{name}.c' for name in [
    'mtx', 'vec', 'mtxvec', 'mtx44',
]]
